# On-boarding
<hr>

## General Lab Onboarding 
As a new lab member, we have implemented systems and tools we use everyday for communication and maintenance of the flow of the lab. Below is a list of things to complete before and during your first day in the lab. Please follow the on-boarding process outlined in below according to your respective position. 

<hr>

## Faculty Collaborator

1. Email the lab manager a copy of your signed CV or Bio Sketch with your signature and the date in the corner of your document. 

2. Complete Required CITI Training and email the lab manager a copy of your certificates.
<ul> 
<li>CITI Good Clinical Practice: Social and Behavioral Research</li>
<li>CITI Human Subjects Training: Social & Behavioral Researchers & Staff</li>
<li>CITI Human Subjects Training: Biomedical Researchers & Staff (if applicable)</li>
<li>CITI Shipping and Transport of Regulated Biological Materials (if applicable)</li>
<li>CITI HIPAA Training</li>
<li>CITI Information Privacy & Security (IPS) Training</li>
</ul>

3. Complete UCLA CANRA Training and email the lab manager the email confirming you have completed your training.
<ul>
<li> To complete UCLA CANRA Training, follow this link: https://uctraining.wufoo.com/forms/q19q32qw05jndzr. </li>
</ul>

4. Attach a copy/screenshot of your California Board of Psychology License information to your on-boarding email you will send to the lab manager.

5. (If applicable) Include your signature and initials in the Delegation of Authority Log sent via DocuSign.

6. Obtain a BruinIRB account and ask the lab manager to be included in the IRB protocols  
<ul>
<li> Email the lab manager and Dr. Ho the following information:
<ul>
<li>Your UCLA Logon ID (Verify your UCLA Logon ID here: https://accounts.iam.ucla.edu/lookup)</li>
<li>Your UCLA UID# (9 digit #)</li>
<li>Your full name (First, Middle, Last)</li>
<li>Your UCLA/Psych email address</li>
<li>Your department and division (Department of Psychology)</li>
</ul>
<li>After your send the necessary information to get a BruinIRB account, the lab manager or Dr. Ho will forward this request to BruinIRB@research.ucla.edu to complete you account creation.</li>
<li>After you create your BruinIRB account, message the lab manager and Dr. Ho to add you to relevant IRB protocols.</li>
</ul> 

7. Request a REDCap account (if needed).
<ul>
<li>Inform the lab manager that you need a REDCap account and they will provide you with the REDCap System Access Request Form and instructions to complete the form. Send the completed form and your CITI HIPAA certification to the lab manager. The lab manager will then forward the request to Martin (mylai@mednet.ucla.edu, REDCap contact personnel). Once your account has been created, you will receive an email confirmation with your Username and Temporary Password. For more information on how to complete the form, contact Dr. Ho or the lab manager.</li>
</ul>

<hr>

## Postdoctoral Scholar

1. Complete and submit your signed UCLA offer letter to Dr. Ho.

2. Meet with HR to submit your on-boarding paperwork and complete your hiring orientation.

3. Once you have completed your on-boarding with HR, create your UCLA Logon ID at the following link: https://accounts.iam.ucla.edu/#/. 

4. Create a BruinCard. Click on the following link for more information on scheduling and obtaining your BruinCard: https://bruincard.ucla.edu/.

5. For parking permit requests, email Tyler (tuione@psych.ucla.edu) and inquire about open lot spaces and different parking permit plans. 

6. For Psychology Building Level-C and after hours access, email Tyler (tuione@psych.ucla.edu) with your UID and cc the lab manager on the email. 

7. Reach out to Life Sciences IT (support@lifesci.ucla.edu) and set up a meeting regarding desktop set-up (Adobe Acrobat, Google chrome, Cisco VPN, connecting to the Psych printer, etc.).

8. Obtain a UCLA Zoom Account and (if needed) request **Zoom Phone** access.
<ul>
<li>To request a UCLA Zoom account, submit a ticket to Life Sciences IT (support@lifesci.ucla.edu), include your full name, position title, and UCLA email you want to use to access Zoom.</li>
<li>Once you receive confirmation from IT about the creation of your Zoom account, Email Tyler (tuione@psych.ucla.edu) with your UCLA email that has already been granted UCLA Zoom access and your UID to request Zoom Phone feature. </li>
</ul>

9. Email the lab manager a copy of your signed CV or Bio Sketch with your signature and the date in the corner of your document. 

10. Schedule a meeting and ask the lab manager to be added to the lab:
<ul>
<li>Asana</li>
<li>Slack</li>
<li>Google calendars</li>
<li>Box (Box browser, Box drive, Box tools)</li>
<li>Mailing List</li>
<li>Lyft Business (if applicable)</li>
</ul>

11. Complete Required CITI Training and email the lab manager a copy of your certificates.
<ul> 
<li>CITI Good Clinical Practice: Social and Behavioral Research</li>
<li>CITI Human Subjects Training: Social & Behavioral Researchers & Staff</li>
<li>CITI Human Subjects Training: Biomedical Researchers & Staff (if applicable)</li>
<li>CITI Shipping and Transport of Regulated Biological Materials (if applicable)</li>
<li>CITI HIPAA Training</li>
<li>CITI Information Privacy & Security (IPS) Training</li>
</ul>

12. Complete UCLA CANRA Training and email the lab manager the email confirming you have completed your training.
<ul>
<li> To complete UCLA CANRA Training, follow this link: https://uctraining.wufoo.com/forms/q19q32qw05jndzr. </li>
</ul>

13. Obtain a BruinIRB account and ask the lab manager to be included in the IRB protocols  
<ul>
<li> Email the lab manager and Dr. Ho the following information:
<ul>
<li>Your UCLA Logon ID (Verify your UCLA Logon ID here: https://accounts.iam.ucla.edu/lookup)</li>
<li>Your UCLA UID# (9 digit #)</li>
<li>Your full name (First, Middle, Last)</li>
<li>Your UCLA/Psych email address</li>
<li>Your department and division (Department of Psychology)</li>
</ul>
<li>After your send the necessary information to get a BruinIRB account, the lab manager or Dr. Ho will forward this request to BruinIRB@research.ucla.edu to complete you account creation.</li>
<li>After you create your BruinIRB account, message the lab manager and Dr. Ho to add you to relevant IRB protocols.</li>
</ul>

14. Request a REDCap account (if needed).
<ul>
<li>Inform the lab manager that you need a REDCap account and they will provide you with the REDCap System Access Request Form and instructions to complete the form. Send the completed form and your CITI HIPAA certification to the lab manager. The lab manager will then forward the request to Martin (mylai@mednet.ucla.edu, REDCap contact personnel). Once your account has been created, you will receive an email confirmation with your Username and Temporary Password. For more information on how to complete the form, contact Dr. Ho or the lab manager.</li>
</ul>

15. Request a DocuSign account (if needed).
<ul>
<li>Inform the lab manager that you need a Docusign account and email support@lifesci.ucla.edu with your name and UCLA email to request *admin access* under your DocuSign account.</li>
</ul>

16. Request a Hoffman2 account (if needed). Follow this link: https://www.hoffman2.idre.ucla.edu/Accounts/Requesting-an-account.html for more information on getting an account. Once you have reviewed the application summary and submitted the account creation form with your information, notify Dr. Ho and the lab manager.

17. (If applicable) Include your signature and initials in the Delegation of Authority Log sent via DocuSign. 

<hr>

## Graduate Student

1. For parking permit requests, email Tyler (tuione@psych.ucla.edu) and inquire about open lot spaces and different parking permit plans. 

2. For Psychology Building Level-C and after hours access, email Tyler (tuione@psych.ucla.edu) with your UID and cc the lab manager on the email. 

3. Reach out to Life Sciences IT (support@lifesci.ucla.edu) and set up a meeting regarding desktop set-up (Adobe Acrobat, Google chrome, Cisco VPN, connecting to the Psych printer, etc.).

4. Obtain a UCLA Zoom Account and (if needed) request **Zoom Phone** access.
<ul>
<li>To request a UCLA Zoom account, submit a ticket to Life Sciences IT (support@lifesci.ucla.edu), include your full name, position title, and UCLA email you want to use to access Zoom.</li>
<li>Once you receive confirmation from IT about the creation of your Zoom account, Email Tyler (tuione@psych.ucla.edu) with your UCLA email that has already been granted UCLA Zoom access and your UID to request Zoom Phone feature. </li>
</ul>

5. Email the lab manager a copy of your signed CV or Bio Sketch with your signature and the date in the corner of your document. 

6. Schedule a meeting and ask the lab manager to be added to the lab:
<ul>
<li>Asana</li>
<li>Slack</li>
<li>Google calendars</li>
<li>Box (Box browser, Box drive, Box tools)</li>
<li>Mailing List</li>
<li>Lyft Business (if applicable)</li>
</ul>

7. Complete Required CITI Training and email the lab manager a copy of your certificates (indicate the expiration of each certificate).
<ul> 
<li>CITI Good Clinical Practice: Social and Behavioral Research</li>
<li>CITI Human Subjects Training: Social & Behavioral Researchers & Staff</li>
<li>CITI Human Subjects Training: Biomedical Researchers & Staff (if applicable)</li>
<li>CITI Shipping and Transport of Regulated Biological Materials (if applicable)</li>
<li>CITI HIPAA Training</li>
<li>CITI Information Privacy & Security (IPS) Training</li>
</ul>

8. Complete UCLA CANRA Training and email the lab manager the email confirming you have completed your training. Follow this link to complete your CANRA training: https://uctraining.wufoo.com/forms/q19q32qw05jndzr. 

9. Obtain a BruinIRB account  
<ul>
<li> Email the lab manager and Dr. Ho the following information:
<ul>
<li>Your UCLA Logon ID (Verify your UCLA Logon ID here: https://accounts.iam.ucla.edu/lookup)</li>
<li>Your UCLA UID# (9 digit #)</li>
<li>Your full name (First, Middle, Last)</li>
<li>Your UCLA/Psych email address</li>
<li>Your department and division (Department of Psychology)</li>
</ul>
<li>After your send the necessary information to get a BruinIRB account, the lab manager or Dr. Ho will forward this request to BruinIRB@research.ucla.edu to complete you account creation.</li>
</ul>

10. Request a REDCap account (if needed).
<ul>
<li>Inform the lab manager that you need a REDCap account and they will provide you with the REDCap System Access Request Form and instructions to complete the form. Send the completed form and your CITI HIPAA certification to the lab manager. The lab manager will then forward the request to Martin (mylai@mednet.ucla.edu, REDCap contact personnel). Once your account has been created, you will receive an email confirmation with your Username and Temporary Password. For more information on how to complete the form, contact Dr. Ho or the lab manager.</li>
</ul>

11. Request a DocuSign account (if needed).
<ul>
<li>Inform the lab manager that you need a Docusign account and email support@lifesci.ucla.edu with your name and UCLA email to request *admin access* under your DocuSign account.</li>
</ul>

12. Request a Hoffman2 account (if needed). Follow this link: https://www.hoffman2.idre.ucla.edu/Accounts/Requesting-an-account.html for more information on getting an account. Once you have reviewed the application summary and submitted the account creation form with your information, notify Dr. Ho and the lab manager.

13. (If applicable) Include your signature and initials in the Delegation of Authority Log sent via DocuSign.

<hr>

## Staff Research Associate

1. Complete and submit your signed UCLA offer letter and employment contract to Dr. Ho.

2. Meet with HR to submit your on-boarding hiring paperwork (CTO Election Form, Background Check Authorization, UCLA Personal Data Form) and complete your hiring orientation.

3. Schedule and complete your Livescan Background check before your official start date and inform Dr. Ho about your scheduled date. You can schedule the Livescan background check by clicking this link: https://police.ucla.edu/services/records-unit/fingerprinting.

4. Once you have received your UCLA ID Number, create your UCLA Logon ID at the following link: https://accounts.iam.ucla.edu/#/. If you have an unexpired UCLA Logon ID (e,g., current UCLA student at the time of employment), you can continue using the old Logon ID, and no need to create a new one. 

5. Create a BruinCard. Click on the following link for more information on scheduling and obtaining your BruinCard: https://bruincard.ucla.edu/. If you have an unexpired BruinCard (e,g., current UCLA student at the time of employment), you can continue using the old BurinCard, and no need to create a new one.

6. For parking permit requests, email Tyler (tuione@psych.ucla.edu) and inquire about open lot spaces and different parking permit plans. 

7. Obtain keys to access the coordinator office. Email tuione@psych.ucla.edu to make a request for a key to the office. 

8. Request Psychology Building and Floor Access. Email Tyler (tuione@psych.ucla.edu) and request BruinCard access to Pritzker Hall, the Psychology Building, and floor C for freezer access. Include your UID in the email and cc the lab manager. 
<ul>
<li>The card readers for building access are located at the side of each entrance, and inside the Pritzker elevator for level C access.</li>
</ul>

9. Reach out to Life Sciences IT (support@lifesci.ucla.edu) to confirm your UCLA Logon Email (@ucla.edu and @g.ucla.edu) and that you have access to your Psychology department email (@psych.ucla.edu).

10. Reach out to Life Sciences IT (support@lifesci.ucla.edu) and set up a meeting regarding desktop set-up (Adobe Acrobat, Google chrome, Cisco VPN, connecting to the Psych printer, etc.).

11. Obtain a UCLA Zoom Account and request **Zoom Phone** access.
<ul>
<li>To request a UCLA Zoom account, submit a ticket to Life Sciences IT (support@lifesci.ucla.edu), include your full name, position title, and UCLA email you want to use to access Zoom.</li>
<li>Once you receive confirmation from IT about the creation of your Zoom account, Email Tyler (tuione@psych.ucla.edu) with your UCLA email that has already been granted UCLA Zoom access and your UID to request Zoom Phone feature. </li>
</ul>

12. Email Mariam (mmoattari@lifesci.ucla.edu) to request editiing access for the CANDY Lab website. 

13. Email the lab manager a copy of your signed CV or Bio Sketch with your signature and the date in the corner of your document. 

14. Schedule a meeting and ask the lab manager to be added to the lab:
<ul>
<li>Asana</li>
<li>Slack</li>
<li>Google calendars</li>
<li>Box (Box browser, Box drive, Box tools)</li>
<li>Mailing List</li>
<li>Lyft Business (if applicable)</li>
</ul>

15. Complete Required CITI Training and email the lab manager a copy of your certificates (indicate the expiration of each certificate).
<ul>
<li>CITI Good Clinical Practice: Social and Behavioral Research</li>
<li>CITI Human Subjects Training: Social & Behavioral Researchers & Staff</li>
<li>CITI Human Subjects Training: Biomedical Researchers & Staff</li>
<li>CITI Shipping and Transport of Regulated Biological Materials</li>
<li>CITI HIPAA Training</li>
<li>CITI Information Privacy & Security (IPS) Training</li>
</ul>

16. Complete UCLA CANRA Training and email the lab manager the email confirming you have completed your training. Follow this link to complete your CANRA training: https://uctraining.wufoo.com/forms/q19q32qw05jndzr. 

17. Complete all necessary UC Training Modules:
<ul>
<li>General Compliance Briefing: UC Ethical Values and Conduct Training</li>
<li>UC Abusive Conduct in the Workplace</li>
<li>UC Cyber Security Awareness Fundamentals</li>
<li>General Compliance Briefing: University of California Ethical Values and Conduct</li>
<li>UC Preventing Harassment & Discrimination: Non-Supervisors</li>
<li>UCLA COVID-19 Prevention</li>
</ul>

18. Obtain a BruinIRB account and ask the lab manager to be included in the IRB protocols
<ul>
<li>UCLA faculty members must request BruinIRB accounts for UCLA students and other researchers who do not meet UCLA Policy 900 PI Eligibility requirements.</li>
<li>Email the lab manager and Dr. Ho the following information:</li>
<ul>
<li>Your UCLA Logon ID (Verify your UCLA Logon ID here: https://accounts.iam.ucla.edu/lookup)</li>
<li>Your UCLA UID# (9 digit #)</li>
<li>Your full name (First, Middle, Last)</li>
<li>Your UCLA/Psych email address</li>
<li>Your department and division (Department of Psychology)</li>
</ul>
<li>After you send the necessary information to get a BruinIRB account, the lab manager or Dr. Ho will forward this request to BruinIRB@research.ucla.edu to complete you account creation.</li>
<li>After you create your BruinIRB account, message the lab manager and Dr. Ho to add you to relevant IRB protocols.</li>
</ul>

19. Request a REDCap account.
<ul>
<li>Inform the lab manager that you need a REDCap account and they will provide you with the REDCap System Access Request Form and instructions to complete the form. Send the completed form and your CITI HIPAA certification to the lab manager. The lab manager will then forward the request to Martin (mylai@mednet.ucla.edu, REDCap contact personnel). Once your account has been created, you will receive an email confirmation with your Username and Temporary Password. For more information on how to complete the form, contact Dr. Ho or the lab manager.</li>
</ul>

20. Request a DocuSign account.
<ul>
<li>Inform the lab manager that you need a Docusign account and email support@lifesci.ucla.edu with your name and UCLA email to request *admin access* under your DocuSign account.</li>
</ul>

21. Request a Hoffman2 account. Follow this link: https://www.hoffman2.idre.ucla.edu/Accounts/Requesting-an-account.html for more information on getting an account. Once you have reviewed the application summary and submitted the account creation form with your information, notify Dr. Ho and the lab manager.

22. Create a CIA account for MRI visit bookings and scanner availability. Follow this link to set up an account: https://cia.ini.usc.edu/home/new_account.

23. Create a Login.gov account for NDA-NIMH Data Uploads.
<ul>
<li>Follow the steps on this page to create a Login.gov account: https://www.login.gov/help/create-account/how-do-i-create-an-account/</li>
<li>Create a NDA account using the Login.gov account:</li>
<ul>
<li>Visit NDA (https://nda.nih.gov/) and click LOGIN</li>
<li>Select Sign in with RAS</li>
<li>Sign in using Login.gov</li>
<li>Fill out the required fields and click Create New NDA account</li>
<li>You'll then be able to sign into NDA using your RAS identity</li>
</ul>
<li>Once you set up your account, email Dr. Ho with the email you used to create the account and your username be added to relevant projects.</li>
</ul>

24. Create a ClinicalTrials.gov account (if applicable).
<ul>
<li>Email the UCLA institutional PRS Administrator, Elaine Cooperstein at ecooperstein@mednet.ucla.edu to request a UCLA Protocol Registration and Results System account for ClinicalTrials.gov. Cc Dr. Ho on the email.</li>
<li>Once your account has been created, you will receive an email with your account credentials and temporary password.</li>
<li>Once you set up your account, email Dr. Ho with the email you used to create the account and your username be added to relevant projects.</li>
</ul>

25. (If applicable) Include your signature and initials in the Delegation of Authority Log sent via DocuSign. 

<hr>

## Volunteer Research Assistant (UCLA Students)

1. Complete the on-boarding survey for RAs: 
<ul>
<li>If assisting with the TIGER project: https://forms.gle/DQh8GeNrpZETTFUq5</li>
<li>If assisting with other projects in lab: https://forms.gle/iHbRBGgztoDJQTs66</li>
</ul>

2. Schedule a meeting and ask the lab manager to be added to the lab:
<ul>
<li>Asana</li>
<li>Slack</li>
<li>Google calendars</li>
<li>Box (Box browser, Box drive, Box tools)</li>
<li>Mailing List</li>
</ul>

3. Complete Required CITI Training and email the lab manager a copy of your certificates.
<ul>
<li>CITI Good Clinical Practice: Social and Behavioral Research</li>
<li>CITI Human Subjects Training: Social & Behavioral Researchers & Staff</li>
<li>CITI Human Subjects Training: Biomedical Researchers & Staff (if applicable)</li>
<li>CITI HIPAA Training</li>
<li>CITI Information Privacy & Security (IPS) Training</li>
</ul>

4. Complete UCLA CANRA Training and email the lab manager the email confirming you have completed your training. Follow this link to complete your CANRA training: https://uctraining.wufoo.com/forms/q19q32qw05jndzr. 

5. Read and sign Dr. Tiffany Ho's CANDY Lab manual via DocuSign.

6. Review and sign the CANDY Lab RA Contract via DocuSign. 

7. (If applicable) Include your signature and initials in the Delegation of Authority Log sent via DocuSign. 

<hr>

## Volunteer Research Assistant (non-UCLA Students, Post-bacc)

1. Complete the volunteer on-boarding forms (provided by the lab manager).
<ul>
<li>
For non-UCLA students and Post-bacc volunteers, complete and the UPAY-585 Patent Acknowledgement form in addition to your volunteer form packet.
</li>
<li>
For high school applicants, make sure a parent or guardian also signs each form in the volunteer on-boarding packet. You will also need to complete the EH&S Online Course - Lab Safety Fundamental Concepts. To complete this EH&S Online Course, click on this link: https://ehs.ucla.edu/training-support/courses and select the Lab Safety Fundamental Concepts course. 
</li>
</ul>

2. Schedule and complete your Livescan Background check before your official start date and inform Dr. Ho about your scheduled date. You can schedule the Livescan background check by clicking this link: https://police.ucla.edu/services/records-unit/fingerprinting. 

3. To complete UCLA trainings, you may be asked to enter your UCLA Log-on ID. Follow this link to create a temporary Log-on ID: https://accounts.iam.ucla.edu/#/ and select the option, "I do not have a 9 digit UCLA ID Number (UID)."

4. Complete the on-boarding survey for RAs:
<ul>
<li>If assisting with the TIGER project: https://forms.gle/DQh8GeNrpZETTFUq5</li>
<li>If assisting with other projects in lab: https://forms.gle/iHbRBGgztoDJQTs66</li>
</ul>

5. Schedule a meeting and ask the lab manager to be added to the lab:
<ul>
<li>Asana</li>
<li>Slack</li>
<li>Google calendars</li>
<li>Box (Box browser, Box drive, Box tools)</li>
<li>Mailing List</li>
</ul>

6. Complete Required CITI Training and email the lab manager a copy of your certificates.
<ul>
<li>CITI Good Clinical Practice: Social and Behavioral Research</li>
<li>CITI Human Subjects Training: Social & Behavioral Researchers & Staff</li>
<li>CITI Human Subjects Training: Biomedical Researchers & Staff (if applicable)</li>
<li>CITI HIPAA Training</li>
<li>CITI Information Privacy & Security (IPS) Training</li>
</ul>

7. Complete UCLA CANRA Training and email the lab manager the email confirming you have completed your training. Follow this link to complete your CANRA training: https://uctraining.wufoo.com/forms/q19q32qw05jndzr. 

8. Read and sign Dr. Tiffany Ho's CANDY Lab manual.

9. Review and sign the CANDY Lab RA Contract.